version: '3'
services:
  lbroundrobbin:
    build:
      context: .
      dockerfile: DockerfileRoundRobin
    container_name: lbroundrobbin
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongodatabase
      - logservice1
      - logservice2
      - logservice3
    networks:
      - my-network

  logservice1:
    build:
      context: .
      dockerfile: DockerfileMessage
    container_name: logservice1
    environment:
      - SERVER_PORT=8080  # Internamente debe ser el mismo puerto para todos
    ports:
      - "35001:8080"  # El puerto interno debe ser 8080
    networks:
      - my-network

  logservice2:
    build:
      context: .
      dockerfile: DockerfileMessage
    container_name: logservice2
    environment:
      - SERVER_PORT=8080
    ports:
      - "35002:8080"
    networks:
      - my-network

  logservice3:
    build:
      context: .
      dockerfile: DockerfileMessage
    container_name: logservice3
    environment:
      - SERVER_PORT=8080
    ports:
      - "35003:8080"
    networks:
      - my-network

  mongodatabase:
    image: mongo:5.0.25-focal
    container_name: mongodatabase
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - my-network

volumes:
  mongodb:
  mongodb_config:

networks:
  my-network:
